// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuW9naLmLeaB_D2hc-fWIdQK0T98JWyw0',
    appId: '1:892123850170:android:62f342c4f311828cac2983',
    messagingSenderId: '892123850170',
    projectId: 'ai-chat-bot-3',
    storageBucket: 'ai-chat-bot-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC597jrL6ZxAyCxLuHmpvaORoRK5sRSa54',
    appId: '1:892123850170:ios:cbba9b489258af7aac2983',
    messagingSenderId: '892123850170',
    projectId: 'ai-chat-bot-3',
    storageBucket: 'ai-chat-bot-3.appspot.com',
    androidClientId: '892123850170-jmbjpn9ohh4tt5enh34l3jdjlkcu5d5l.apps.googleusercontent.com',
    iosClientId: '892123850170-rnnh6a6miktnivdlfhkgpsq94d4c2c0h.apps.googleusercontent.com',
    iosBundleId: 'com.ide.codeKit.translator',
  );

}